config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/categories' => 'categories#index'
  get '/categories/new' => 'categories#new', as: 'new_category'
  post '/categories' => 'categories#create', as: 'create_category'

  get '/categories/show/:id' => 'categories#show', as: 'show_category'
  get '/categories/edit/:id' => 'categories#edit', as: 'edit_category'
  patch '/categories/:id' => 'categories#update', as: 'update_category'
  delete '/categories/:id' => 'categories#delete', as: 'delete_category'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :category, presence: true, length: {maximum: 20}
    validates :details, presence: true, length: {minimum: 10, maximum: 100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)

        if @category.save
            redirect_to categories_path
        else
            render :new
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        @category.update(category: params[:category][:category], details: params[:category][:details])
        redirect_to categories_path
    end

    def delete
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to categories_path
    end

    def show
        @category = Category.find(params[:id])
    end

    private
    def category_params
        params.require(:category).permit(:category, :details)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h1>Journal Categories - Edit Entry</h1>
<hr class="my-4">
<%= form_with scope: :category ,url: update_category_path, method: :patch, local: true do |f| %>
    
    <%= f.label 'Category Title' %><br>
    <%= f.text_field :category %><br>

    <%= f.label 'Category Details' %><br>
    <%= f.text_area :details %><br>

    <%= f.submit "Edit Category" %>
<% end %>

app/views/categories/index.html.erb
<h1>Journal Categories</h1>
<hr class="my-4">
<table class="table table-striped">
    <thead>
        <tr>
            <th>id</th>
            <th>Category</th>
            <th>Details</th>
            <th>Edit</th>
            <th>Delete</th>
            <th>Detail</th>
        </tr>
    </thead>
    <tbody>
        <% @categories.each do |category| %>
            <tr>
                <td><%= category.id %></td>
                <td><%= category.category %></td>
                <td><%= category.details %></td>
                <td><%= button_to "Edit", edit_category_path(category.id), {method: :get, class: "btn btn-info"} %></td>
                <td><%= button_to "Delete", delete_category_path(category.id), {method: :delete, class: "btn btn-danger"} %></td>
                <td><%= button_to "Show", show_category_path(category.id), {method: :get, class: "btn btn-secondary"} %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= button_to '+ New Category' , new_category_path, {method: :get, class: "btn btn-primary"} %>

app/views/categories/new.html.erb
<h1>Journal Categories - Create New</h1>
<hr class="my-4">
<%= form_with scope: :category, url: create_category_path, local: true do |f| %>
    
    <p>
        <% if @category.errors.any?  %>
            <ul>
                <% @category.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                <% end %>
            </ul>
        <% end %>
    </p>
    
    <p>
    <%= f.label 'Category Title' %>
    <%= f.text_field :category %>
    </p>
    
    <p>
    <%= f.label 'Category Details' %>
    <%= f.text_area :details %>
    </p>
    

    <%= f.submit "Create" %>
<% end %>

app/views/categories/show.html.erb
<h1>Journal Categories - Show Details</h1>
<hr class="my-4">
<table class="table table-striped">
    <thead>
        <tr>
            <th>id</th>
            <th>Category</th>
            <th>Details</th>
            <th>Created</th>
            <th>Last Updated</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @category.id %></td>
            <td><%= @category.category %></td>
            <td><%= @category.details %></td>
            <td><%= @category.created_at %></td>
            <td><%= @category.updated_at %></td>
        </tr>
    </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    

    <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>